#ifndef CLIENT_CONSTANTS_H
#define CLIENT_CONSTANTS_H

#define TILE_SIZE 25
#define FPS 30

#define SCREEN_WIDTH 1024
#define SCREEN_HEIGHT 768

#define WORLD_WIDTH 1200
#define WORLD_HEIGHT 1200

enum class Layer { BODY = 0, HEAD = 1, HELMET = 2, WEAPON = 3, SHIELD = 4 };

#define TILE_SIZE 25

#endif  // CLIENT_CONSTANTS_H
