[equipable.espada]
name = 'Espada'
type = 'Weapon'
magic = false 
min_stat = 2
max_stat = 5

[equipable.hacha]
name = 'Hacha'
type = 'Weapon'
magic = false
min_stat = 4
max_stat = 5

[equipable.vara_fresno]
name = 'Vara de fresno'
type = 'Weapon'
magic = true
min_stat = 4
max_stat = 5
