# =========================================
# TILES :::::::::::::::::::::::::::::::::::
# =========================================
[[tiles]]
id = 0
name = "Agua"
width = 4
height = 4
unwalkable = [0, 0, 4, 4]

[[tiles]]
id = 1
name = "Pasto"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 2
name = "Pasto camino izq."
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 3
name = "Pasto camino horizontal"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 4
name = "Pasto camino der."
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 5
name = "Pasto camino arriba"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 6
name = "Pasto camino vertical"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 7
name = "Pasto camino abajo"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 8
name = "Pasto camino cruz"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 9
name = "Pasto camino esq. 1"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 10
name = "Pasto camino esq. 2"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 11
name = "Pasto camino esq. 3"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 12
name = "Pasto camino esq. 4"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 13
name = "Pasto camino T 1"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 14
name = "Pasto camino T 2"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 15
name = "Pasto camino T 3"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 16
name = "Pasto camino T 4"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 17
name = "Arena"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 18
name = "Arena camino arriba"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 19
name = "Arena camino esq. 1"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 20
name = "Arena camino T 1"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 21
name = "Arena camino esq. 2"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 22
name = "Arena camino vertical"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 23
name = "Arena camino T 3"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 24
name = "Arena camino cruz"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 25
name = "Arena camino T 4"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 26
name = "Arena camino esq. 3"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 27
name = "Arena camino T 2"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 28
name = "Arena camino esq. 4"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 29
name = "Arena camino izq."
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 30
name = "Arena camino horizontal"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 31
name = "Arena camino abajo"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 32
name = "Arena camino der."
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 33
name = "Arena ladrillo"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 34
name = "Nieve"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 35
name = "Nieve 2"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 36
name = "Nieve 3"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 37
name = "Nieve tierra"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 38
name = "Mazmorra pared arriba"
width = 4
height = 4
unwalkable = [0, 0, 4, 4]

[[tiles]]
id = 39
name = "Mazmorra pared abajo"
width = 4
height = 4
unwalkable = [0, 2, 4, 2]

[[tiles]]
id = 40
name = "Mazmorra pared izq"
width = 4
height = 4
unwalkable = [0, 0, 2, 4]

[[tiles]]
id = 41
name = "Mazmorra pared der"
width = 4
height = 4
unwalkable = [2, 0, 2, 4]

[[tiles]]
id = 42
name = "Mazmorra pared esq. 4"
width = 4
height = 4
unwalkable = [0, 0, 2, 4]

[[tiles]]
id = 43
name = "Mazmorra pared esq. 3"
width = 4
height = 4
unwalkable = [2, 0, 2, 4]

[[tiles]]
id = 44
name = "Mazmorra pared esq. 2"
width = 4
height = 4
unwalkable = [0, 2, 2, 2]

[[tiles]]
id = 45
name = "Mazmorra pared esq. 1"
width = 4
height = 4
unwalkable = [2, 2, 2, 2]

[[tiles]]
id = 46
name = "Mazmorra L 1"
width = 4
height = 4
unwalkable = [0, 0, 4, 4]

[[tiles]]
id = 47
name = "Mazmorra L 2"
width = 4
height = 4
unwalkable = [0, 0, 4, 4]

[[tiles]]
id = 48
name = "Mazmorra L 3"
width = 4
height = 4
unwalkable = [2, 0, 2, 2]
inverse = true

[[tiles]]
id = 49
name = "Mazmorra L 3"
width = 4
height = 4
unwalkable = [0, 0, 2, 2]
inverse = true

[[tiles]]
id = 50
name = "Mazmorra piso"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 51
name = "Pasto costa 1"
width = 2
height = 2
unwalkable = [0, 0, 1, 2]

[[tiles]]
id = 52
name = "Pasto costa 2"
width = 2
height = 2
unwalkable = [1, 0, 1, 2]

[[tiles]]
id = 53
name = "Pasto costa 4"
width = 2
height = 2
unwalkable = [1, 0, 2, 1]

[[tiles]]
id = 54
name = "Pasto costa 3"
width = 2
height = 2
unwalkable = [0, 0, 2, 1]

[[tiles]]
id = 55
name = "Pasto costa esq 1"
width = 2
height = 2
unwalkable = [1, 1, 1, 1]

[[tiles]]
id = 56
name = "Pasto costa esq 3"
width = 2
height = 2
unwalkable = [1, 0, 1, 1]

[[tiles]]
id = 57
name = "Pasto costa esq 2"
width = 2
height = 2
unwalkable = [0, 1, 1, 1]

[[tiles]]
id = 58
name = "Pasto costa esq 4"
width = 2
height = 2
unwalkable = [0, 0, 1, 1]

[[tiles]]
id = 59
name = "Pasto costa L 1"
width = 2
height = 2
unwalkable = [1, 1, 1, 1]
inverse = true

[[tiles]]
id = 60
name = "Pasto costa L 3"
width = 2
height = 2
unwalkable = [1, 0, 1, 1]
inverse = true

[[tiles]]
id = 61
name = "Pasto costa L 2"
width = 2
height = 2
unwalkable = [0, 1, 1, 1]
inverse = true

[[tiles]]
id = 62
name = "Pasto costa L 4"
width = 2
height = 2
unwalkable = [0, 0, 1, 1]
inverse = true


[[tiles]]
id = 63
name = "Arena costa 1"
width = 2
height = 2
unwalkable = [0, 0, 1, 2]

[[tiles]]
id = 64
name = "Arena costa 2"
width = 2
height = 2
unwalkable = [1, 0, 1, 2]

[[tiles]]
id = 65
name = "Arena costa 4"
width = 2
height = 2
unwalkable = [1, 0, 2, 1]

[[tiles]]
id = 66
name = "Arena costa 3"
width = 2
height = 2
unwalkable = [0, 0, 2, 1]

[[tiles]]
id = 67
name = "Arena costa esq 1"
width = 2
height = 2
unwalkable = [1, 1, 1, 1]

[[tiles]]
id = 68
name = "Arena costa esq 3"
width = 2
height = 2
unwalkable = [1, 0, 1, 1]

[[tiles]]
id = 69
name = "Arena costa esq 2"
width = 2
height = 2
unwalkable = [0, 1, 1, 1]

[[tiles]]
id = 70
name = "Arena costa esq 4"
width = 2
height = 2
unwalkable = [0, 0, 1, 1]

[[tiles]]
id = 71
name = "Arena costa L 1"
width = 2
height = 2
unwalkable = [1, 1, 1, 1]
inverse = true

[[tiles]]
id = 72
name = "Arena costa L 3"
width = 2
height = 2
unwalkable = [1, 0, 1, 1]
inverse = true

[[tiles]]
id = 73
name = "Arena costa L 2"
width = 2
height = 2
unwalkable = [0, 1, 1, 1]
inverse = true

[[tiles]]
id = 74
name = "Arena costa L 4"
width = 2
height = 2
unwalkable = [0, 0, 1, 1]
inverse = true

[[tiles]]
id = 75
name = "Nieve costa 1"
width = 2
height = 2
unwalkable = [0, 0, 1, 2]

[[tiles]]
id = 76
name = "Nieve costa 2"
width = 2
height = 2
unwalkable = [1, 0, 1, 2]

[[tiles]]
id = 77
name = "Nieve costa 4"
width = 2
height = 2
unwalkable = [1, 0, 2, 1]

[[tiles]]
id = 78
name = "Nieve costa 3"
width = 2
height = 2
unwalkable = [0, 0, 2, 1]

[[tiles]]
id = 79
name = "Nieve costa esq 1"
width = 2
height = 2
unwalkable = [1, 1, 1, 1]

[[tiles]]
id = 80
name = "Nieve costa esq 3"
width = 2
height = 2
unwalkable = [1, 0, 1, 1]

[[tiles]]
id = 81
name = "Nieve costa esq 2"
width = 2
height = 2
unwalkable = [0, 1, 1, 1]

[[tiles]]
id = 82
name = "Nieve costa esq 4"
width = 2
height = 2
unwalkable = [0, 0, 1, 1]

[[tiles]]
id = 83
name = "Nieve costa L 1"
width = 2
height = 2
unwalkable = [1, 1, 1, 1]
inverse = true

[[tiles]]
id = 84
name = "Nieve costa L 3"
width = 2
height = 2
unwalkable = [1, 0, 1, 1]
inverse = true

[[tiles]]
id = 85
name = "Nieve costa L 2"
width = 2
height = 2
unwalkable = [0, 1, 1, 1]
inverse = true

[[tiles]]
id = 86
name = "Nieve costa L 4"
width = 2
height = 2
unwalkable = [0, 0, 1, 1]
inverse = true

[[tiles]]
id = 87
name = "Arena limite 1"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 88
name = "Arena limite 2"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 89
name = "Arena limite 3"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 90
name = "Arena limite 4"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 91
name = "Arena limite esq 1"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 92
name = "Arena limite esq 2"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 93
name = "Arena limite esq 3"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 94
name = "Arena limite esq 4"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 95
name = "Arena limite L 1"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 96
name = "Arena limite L 2"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 97
name = "Arena limite L 3"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

[[tiles]]
id = 98
name = "Arena limite L 4"
width = 4
height = 4
unwalkable = [0, 0, 0, 0]

# =========================================
# COLLIDERS :::::::::::::::::::::::::::::::
# =========================================



[[colliders]]
id = 0
name = "Carreta"
width = 3
height = 2
unwalkable = [0,1,3,1]

[[npcs]]
id = 0
name = "Cura"
width = 1
height = 2
unwalkable = [0,1,1,1]

[[npcs]]
id = 1
name = "Comerciante"
width = 1
height = 2
unwalkable = [0,1,1,1]

[[npcs]]
id = 2
name = "Banquero"
width = 1
height = 2
unwalkable = [0,1,1,1]