[server.players]
path = "/server/player_stats.toml"

[server.creatures]
path = "/server/creature_stats.toml"

[server.cooldowns]
path = "/server/cooldowns.toml"

[server.items]
path = "/server/items.toml"