# cat = [primer_arch.png, ultimo_arch.png]
[file_ids]
tiles = [1, 99]
colliders = [0, 65]
npcs = [0, 3]
loot = [0, 2]
vfx_attack = [0, 22]
vfx_other = [0, 1]

body = [0, 9]
head = [0, 13]
equipment = [0, 28]

goblin = [0, 4]
skeleton = [0, 3]
zombie = [0, 0]
spider = [0, 2]
orc = [2, 2]
golem = [3, 6]

game_ui = [0, 6]
hud_items = [0, 28]

safe_zones = [0, 0]