# cat = [primer_arch.png, ultimo_arch.png]
[file_ids]
tiles = [0,98]
colliders = [0,65]
npcs = [0,2]
body = [0, 6]
head = [0, 13]
goblin = [0, 4]
skeleton = [0, 3]
zombie = [0, 0]
spider = [0, 2]
orc = [2, 2]
golem = [3, 6]