[biomes.beach]
id = 0
tiles = [0, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]
creatures = [0, 2]
variations = [0, 1, 2, 4]

[biomes.snowland]
id = 1
tiles = [34, 35, 36, 37]
creatures = [0, 1]
variations = [0, 1, 2, 4]

[biomes.forest]
id = 2
tiles = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
creatures = [0, 3]
variations = [0, 1, 2, 4]

[biomes.dungeon]
id = 4
tiles = [38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
creatures = [0, 1, 2, 3, 4, 5]
variations = [2, 3, 5, 6]