[weapons.sword]
id = 1
type = "melee"
min_damage = 2
max_damage = 5
range = 1

[weapons.axe]
id = 2
type = "melee"
min_damage = 4
max_damage = 5
range = 1

[weapons.hammer]
id = 3
type = "melee"
min_damage = 1
max_damage = 9
range = 1


[weapons.ash_stick]
id = 4
type = "magic_damage"
min_effect = 2
max_effect = 4
mana_cost = 5
range = 5

[weapons.elven_flute]
id = 5
type = "magic_healing"
min_effect = 50
max_effect = 100
mana_cost = 100
range = 5

[weapons.knotty_staff]
id = 6
type = "magic_damage"
min_effect = 4
max_effect = 8
mana_cost = 15
range = 5

[weapons.socketed_staff]
id = 7
type = "magic_damage"
min_effect = 8
max_effect = 20
mana_cost = 30
range = 7


[weapons.simple_bow]
id = 8
type = "ranged"
min_effect = 1
max_effect = 4
range = 5

[weapons.compound_bow]
id = 9
type = "ranged"
min_effect = 4
max_effect = 16
range = 7


[armors.leather]
id = 10
min_defense = 15
max_defense = 30

[armors.plate]
id = 11
min_defense = 2
max_defense = 6

[armors.blue_tunic]
id = 12
min_defense = 6
max_defense = 10


[helmets.hood]
id = 13
min_defense = 1
max_defense = 4

[helmets.iron_helmet]
id = 14
min_defense = 4
max_defense = 8

[helmets.magic_hat]
id = 15
min_defense = 4
max_defense = 12


[shields.turtle]
id = 16
min_defense = 1
max_defense = 2

[shields.iron]
id = 17
min_defense = 11
max_defense = 4


[potions.health]
id = 18
type = "health"
effect = 100

[potions.mana]
id = 19
type = "mana"
effect = 100