[weapons.bare_hand]
id = 0
price = 0
min_value = 1
max_value = 3
range = 1
mana_cost = 0

[weapons.sword]
id = 1
price = 230
min_value = 2
max_value = 5
range = 1
mana_cost = 0

[weapons.axe]
id = 2
price = 560
min_value = 4
max_value = 5
range = 1
mana_cost = 0

[weapons.hammer]
id = 3
price = 610
min_value = 1
max_value = 9
range = 1
mana_cost = 0

[weapons.ash_stick]
id = 4
price = 370
min_value = 2
max_value = 4
range = 4
mana_cost = 5

# TODO: la solución puede ser agregarles un campo para ver si son de curación o un effect como las pociones y que uno sea daño y el otro aprovecha el HEALTH 
# [weapons.elven_flute]
# id = 5
# price = 500
# min_value = 150
# max_value = 300
# range = 0            # "sobre el jugador que restaura la vida"
# mana_cost = 100

[weapons.knotty_staff]
id = 6
price = 710
min_value = 4
max_value = 8
range = 5
mana_cost = 15

[weapons.socketed_staff]
id = 7
price = 1120
min_value = 8
max_value = 20
range = 6
mana_cost = 30

[weapons.simple_bow]
id = 8
price = 520
min_value = 1
max_value  = 4
range = 5
mana_cost = 0

[weapons.compound_bow]
id = 9
price = 880
min_value = 4
max_value  = 16
range = 7
mana_cost = 0



[armors.leather]
id = 10
price = 670
min_value = 2
max_value = 6

[armors.plate]
id = 11
price = 1420
min_value = 15
max_value = 30

[armors.blue_tunic]
id = 12
price = 890
min_value = 6
max_value = 10



[helmets.hood]
id = 13
price = 550
min_value = 1
max_value = 4

[helmets.iron_helmet]
id = 14
price = 710
min_value = 4
max_value = 8

[helmets.magic_hat]
id = 15
price = 850
min_value = 4
max_value = 12



[shields.turtle]
id = 16
price = 390
min_value = 1
max_value = 2

[shields.iron]
id = 17
price = 610
min_value = 1
max_value = 4



[usables.health]
id = 18
price = 90
type = 0
effect = 170

[usables.mana]
id = 19
price = 110
type = 1
effect = 130