[music]
creator = { paths = ["/music/creator.mid"], volume = 16 }
login = { paths = ["/music/login.mid"], volume = 8 }
forest = { paths = ["/music/forest.mid"], volume = 16 }

[sfx]
death = { paths = ["/sfx/death.wav"], volume = 16 }
despawn = { paths = ["/sfx/despawn.wav"], volume = 64 }
footstep = { paths = ["/sfx/step1.wav", "/sfx/step2.wav"], volume = 8 }
heal = { paths = ["/sfx/heal.wav"], volume = 128 }
meditation = { paths = ["/sfx/meditation.wav"], volume = 128 }
resurrection = { paths = ["/sfx/resurrection.wav"], volume = 16 }
spawn = { paths = ["/sfx/spawn.wav"], volume = 16 }
fists_attack = { paths = ["/sfx/attacks/melee/fists.wav"], volume = 16 }
sword_attack = { paths = ["/sfx/attacks/melee/sword1.wav", "/sfx/attacks/melee/sword2.wav", "/sfx/attacks/melee/sword3.wav"], volume = 16 }
axe_attack = { paths = ["/sfx/attacks/melee/axe.wav"], volume = 16 }
hammer_attack = { paths = ["/sfx/attacks/melee/hammer.wav"], volume = 16 }
magic_arrow_spell = { paths = ["/sfx/attacks/spell/magic_arrow.wav"], volume = 16 }
heal_spell = { paths = ["/sfx/attacks/spell/heal.wav"], volume = 16 }
missile_spell = { paths = ["/sfx/attacks/spell/missile.wav"], volume = 16 }
explosion_spell = { paths = ["/sfx/attacks/spell/explosion.wav"], volume = 16 }
bow_attack = { paths = ["/sfx/attacks/bow/arrow1.wav", "/sfx/attacks/bow/arrow2.wav"], volume = 16 }